openapi: 3.1.0
info:
  version: 1.0.0
  title: Example.com
  termsOfService: 'https://example.com/terms/'
  contact:
    email: junk@etvoila.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description:
    $ref: ./info-description.md
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Users
    description: Represents a user playing a come on the site
  - name: Games
    description: Represents games on the site
  - name: Events
    description: This provides a sequential record of all that has happened on the site.
    externalDocs:
      description: Here you can read about how events work in detail
      url: https://developer.saxo
  - name: Site Statistics
    description: Statistics on site usage
  
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  /events: 
    $ref: paths/events.yaml
  /games: 
    $ref: paths/games.yaml
  /games/{GameId}: 
    $ref: paths/games@{GameId}.yaml
  /games/{GameId}/moves: 
    $ref: paths/games@{GameId}@moves.yaml
  /gamesummaries: 
    $ref: paths/gamesummaries.yaml
  /sitestatistics: 
    $ref: paths/sitestatistics.yaml
  /users: 
    $ref: paths/users.yaml
  
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
      
